version: '3.8'

services:
  mysqldb:
    # image: mysql/mysql-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysqldb
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: events
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysqldbvol:/var/lib/mysql

volumes:
  mysqldbvol:
