version: '3.8'

services:
  mysqldb:
    image: mysql/mysql-server:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: mysqldb
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: events
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysqldbvol:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  minio1:
    image: quay.io/minio/minio
    container_name: minio1
    entrypoint: /usr/bin/docker-entrypoint.sh
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "F:\\minio:/data"
    networks:
      - default

#   fastapi:
#     build:
#       context: ./fastapi sample app
#       dockerfile: Dockerfile
#     container_name: fastapi_service
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./fastapi_service:/app
#     environment:
#       - ENV=development
#     networks:
#       - default

# networks:
#   default:
#     driver: bridge

volumes:
  mysqldbvol:
